//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BEUBiblioteca
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Libro
    {
        public int idLibro { get; set; }
        public string Titulo { get; set; }
        public string Autor { get; set; }
        public string ISBN { get; set; }
        public Nullable<System.DateTime> Fecha_publicacion { get; set; }
        public Nullable<int> Numero_de_Ejemplares { get; set; }
        public Nullable<int> idCategoria { get; set; }
    
        public virtual tblCategoria tblCategoria { get; set; }
    }
}
