//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BEUBiblioteca
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Video
    {
        public int idVideo { get; set; }
        public string titulo { get; set; }
        public string fecha_publicacion { get; set; }
        public string duracion_minutos { get; set; }
        public Nullable<int> idCategoria { get; set; }
    
        public virtual tblCategoria tblCategoria { get; set; }
    }
}
